name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/check-and-publish.yml') }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - uses: Swatinem/rust-cache@v2
      - run: deno task ok
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: sudo apt-get update && sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - run: rustup target add x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu
      - run: deno task build:all
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: deno publish
      - if: github.event_name != 'push' || github.ref != 'refs/heads/main'
        run: deno publish --dry-run
